language: julia
os:
- linux
- osx
julia:
- 1.0
- nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
git:
  depth: 1
after_success:
- julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Coverage");'
- julia -e 'import ellistools; joinpath(dirname(pathof(ellistools)), ".."); include(joinpath("docs", "make.jl"))'
- julia -e 'import ellistools; joinpath(dirname(pathof(ellistools)), ".."); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
